export const ACTION_TYPE = {
	ADD_COMMENT: 'ADD_COMMENT',
	CLOSE_MODAL: 'CLOSE_MODAL',
	LOGOUT: 'LOGOUT',
	OPEN_MODAL: 'OPEN_MODAL',
	REMOVE_COMMENT: 'REMOVE_COMMENT',
	REMOVE_PRODUCT_TO_CART: 'REMOVE_PRODUCT_TO_CART',
	RESET_DATA: 'RESET_DATA',
	SET_CART_DATA: 'SET_CART_DATA',
	SET_LOADING_END: 'SET_LOADING_END',
	SET_LOADING_START: 'SET_LOADING_START',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	SET_PRODUCT_CATEGORIES: 'SET_PRODUCT_CATEGORIES',
	SET_USER: 'SET_USER',
	SET_PRODUCTS: 'SET_PRODUCTS',
	UPDATE_CART: 'UPDATE_CART',
	UPDATE_PRODUCT_LIST: 'UPDATE_PRODUCT_LIST',
	SET_CART_ERROR: 'SET_CART_ERROR',
	SET_CART_LOADING: 'SET_CART_LOADING',
	SET_PRODUCT_ERROR: 'SET_PRODUCT_ERROR',
	SET_PRODUCT_LOADING: 'SET_PRODUCT_LOADING',
	SET_LAST_PAGE: 'SET_LAST_PAGE',
};

export enum EAppActionTypes {
	ADD_COMMENT = 'ADD_COMMENT',
	CLOSE_MODAL = 'CLOSE_MODAL',
	LOGOUT = 'LOGOUT',
	OPEN_MODAL = 'OPEN_MODAL',
	UPDATE_PRODUCT_LIST = 'UPDATE_PRODUCT_LIST',
}

export enum ECartActionTypes {
	SET_CART_DATA = 'SET_CART_DATA',
	UPDATE_CART = 'UPDATE_CART',
	REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART',
	RESET_DATA = 'RESET_DATA',
	SET_CART_ERROR = 'SET_CART_ERROR',
	SET_CART_LOADING = 'SET_CART_LOADING',
}

export enum EProductActionTypes {
	ADD_COMMENT = 'ADD_COMMENT',
	REMOVE_COMMENT = 'REMOVE_COMMENT',
	SET_PRODUCT_DATA = 'SET_PRODUCT_DATA',
	SET_PRODUCT_ERROR = 'SET_PRODUCT_ERROR',
	SET_PRODUCT_LOADING = 'SET_PRODUCT_LOADING',
	SET_PRODUCT_CATEGORIES = 'SET_PRODUCT_CATEGORIES',
	SET_PRODUCTS = 'SET_PRODUCTS',
	SET_LAST_PAGE = 'SET_LAST_PAGE',
}

export enum EUserActionTypes {
	SET_USER = 'SET_USER',
	LOGOUT = 'LOGOUT',
}
