export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	SET_CART_DATA: 'SET_CART_DATA',
	UPDATE_CART: 'UPDATE_CART',
	UPDATE_PRODUCT_LIST: 'UPDATE_PRODUCT_LIST',
	RESET_DATA: 'RESET_DATA',
	UPDATE_IS_LOADING: 'UPDATE_IS_LOADING',
};
