export enum ECartActionTypes {
	SET_CART_DATA = 'SET_CART_DATA',
	UPDATE_CART = 'UPDATE_CART',
	REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART',
	RESET_DATA = 'RESET_DATA',
	SET_CART_ERROR = 'SET_CART_ERROR',
	SET_CART_LOADING = 'SET_CART_LOADING',
}
